#!/bin/bash

# Function to generate a random password
generate_password() {
    local length="$1"
    tr -dc 'A-Za-z0-9_!@#$%^&*()-+=' < /dev/urandom | head -c "$length"
}

# Function to copy text to the clipboard
copy_to_clipboard() {
    local text="$1"
    echo -n "$text" | xclip -selection clipboard
}

# Main
echo "Password Generator"

# Set default password length to 16
default_length=16
password_length="$default_length"

# Check if a custom length is provided as a parameter
if [ $# -eq 1 ]; then
    password_length="$1"
fi

if [[ ! "$password_length" =~ ^[0-9]+$ ]]; then
    echo "Invalid input. Please enter a valid number."
    exit 1
fi

password=$(generate_password "$password_length")

copy_to_clipboard "$password"  # Copy password to clipboard

echo "Password copied to clipboard."

